# name: Publish
# on:
#   push:
#     tags:
#       - '*.*.*'

# env:
#   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

# jobs:
#   release:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           cache: npm
#           node-version: '14'
#       - name: Set output
#         id: vars
#         run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
#       - run: |
#           npm ci
#           node ./scripts/build-and-publish.js
#       - name: Create release pull request
#         run: hub pull-request --no-edit --head=release-${{ steps.vars.outputs.tag }}
