name: Create release notes pull request

on:
  push:
    branches:
      - 'releases/*'

env:
  GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: hub pull-request --no-edit --base=main --head=${{ github.ref_name }}
