name: Create pull request for release notes

on:
  push:
    branches:
      - 'release-*.*.*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create release pull request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: 'main'
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
