name: Validate PR title
on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

env:
  GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

jobs:
  validate-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amannn/action-semantic-pull-request@v4
