name: Publish

on:
  push:
    branches:
      - '!*'
    tags:
      - '*.*.*'

env:
  GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - uses: actions/checkout@v2
        with:
          branch: 'release-${{ steps.vars.outputs.tag }}'
          fetch-depth: 0
      - name: Create release pull request
        run: hub pull-request --no-edit --head=release-${{ steps.vars.outputs.tag }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build and publish
        run: node ./scripts/build-and-publish.js
